version: "3.3"
services:
  app:
    build:
      context: . #current directory
      dockerfile: Dockerfile #use the dockerfile called Dockerfile
    ports:
      - "9000:9000" #forward port from my app to the OS
    networks:
      - backend
  #redis:
  #  image: "redis:alpine" #could be redis or redis alphine
  #  networks:
  #    - backend
  #  ports:
  #    - "6379:6379" #forward port from my app to the OS

  database:
    image: postgres:latest
    container_name: golang-docker-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  networks:
    backend: # network to communicate containers with each other

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database
    ports:
      - "5050:80"
    networks:
      backend: # network to communicate containers with each other
    restart: unless-stopped


#to build Docker-compose
## docker-compose up --build         